language: common-lisp
sudo: false

addons:
  postgresql: "9.4"

services:
  - postgresql

env:
  global:
    - PATH=$HOME/.roswell/bin:$PATH
    - ROSWELL_INSTALL_DIR=$HOME/.roswell

install:
  # Install Roswell
  - curl -L https://raw.githubusercontent.com/roswell/roswell/release/scripts/install-for-ci.sh | sh
  - ros install prove
  - ros install qlot
  - qlot install

before_script:
  - psql -c 'create database "reddit";' -U postgres
  - psql -c "CREATE USER test WITH PASSWORD 'test';" -U postgres
  - ros run -- --eval '(asdf:load-asdf "reddit-db.asdd")(quit)'

script:
  - run-prove reddit-test.asd
